### PR TITLE
get summary plot

### PR DESCRIPTION
**Pull request by Benjamin15**
Hi,

When i use the function summary_plot, sometimes i want to get the summary plot.

Currently, i think this is not possible, so i suggest this PR.

In the function summary_plot, I had a parameter, get_png. When the parameter get_png is True, we return a BytesIO object which contains the summary plot.

### CODE REVIEW

**Comment by slundberg** [comment]
Sorry for the delay I have been out sick. Is there a reason you can't do this after drawing by using the `show=False` option?

**Comment by Benjamin15** [comment]
Hey, 
No problem,
Yes, I want to generate a HTML website with the plot, not just a jupyter.
I have two ways to do this : 
- Use the matplotlib object
- Use a BytesIO which contains a png file

I think the second choice is the better way.

**Comment by slundberg** [comment]
Right but can't you run the plot with `show=False` and then just follow that with?: 
```
file = BytesIO()
pl.savefig(file, format='png', bbox_inches="tight")
```

...since savefig will just work with the current active figure.

**Comment by Benjamin15** [comment]
That work ! I didn't know that matplotlib is a global variable or a Singleton. Thanks for the learning !

**Pull request closed without merging**
