### PR TITLE
Fix: convert DataFrame to ndarray for Explanation.data

### LINKED ISSUE #1625: Scatter plots fail with shap_values.display_data = Pandas dataframe
First of all we would like to thank the team of developers for their efforts. It's a great library.

This new version of SHAP 0.37 that will generate an object to store shap_values works with list type data, NumPy and Pandas but there are times when these types are changed to generate errors. This is an example and I would like you to review the code to be compatible with these types.

Versión SHAP 0.37 (clone github 6 dic). The stable 0.37 has some other issues.

```python
import xgboost
import shap

X,y = shap.datasets.adult()
model = xgboost.XGBClassifier().fit(X, y)

explainer = shap.Explainer(model)
shap_values = explainer(X[:1000])

X_display,y = shap.datasets.adult(display=True)
shap_values.display_data = X_display.values   # NumPy

shap.plots.scatter(shap_values[:, "Age"], color=shap_values[:,"Workclass"])
```

This code work well but if we use a Pandas dataframe variable in display_data

```python
shap_values.display_data = X_display   # Pandas dataframe

shap.plots.scatter(shap_values[:, "Age"], color=shap_values[:,"Workclass"])
```

```
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'reshape'
```

### PR DESCRIPTION
**Pull request by danieleongari**
## Overview

Closes https://github.com/shap/shap/issues/1625

Description of the changes proposed in this pull request:

Convert `DataFrame` to `ndarray` for `Explanation.data` in a `KernelExplainer`, when for some reason, X is a DataFrame.
 `Explanation.data` being a DataFrame causes problems later, at the plotting stage.

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Review by thatlittleboy — CHANGES_REQUESTED** [review]
Hi @danieleongari , sorry for the delayed review. The changes you propose make sense to me in general. May I request you add a minimal test to ensure we don't regress this behaviour in the future?

**Comment by danieleongari** [comment]
@thatlittleboy good point. I will try to work on it this evening and let you know ASAP if I succeed to understand the testing structure and adding this.

**Comment by danieleongari** [comment]
Adding the test `test_kernel_shap_with_dataframe_explaination`.
This is how the code would fail if my correction was commented (top panel), perfectly reproducing the issue https://github.com/shap/shap/issues/1625.
image

With my correction the test runs smoothly!

**Review by thatlittleboy — APPROVED** [review]
Thanks for the contribution!

husky-jumping-shipit

**Pull request merged**
