### PR TITLE
enable summary_plot to return the figure if show=False

### PR DESCRIPTION
**Pull request by zkurtz**
I was trying to access the underlying pyplot figure so that I could export it to a .png. This solved my problem. Is there an even easier way?

### CODE REVIEW

**Comment by chrisadas** [comment]
I was just thinking about the same thing.

https://github.com/slundberg/shap/issues/197

**Comment by slundberg** [comment]
Hmm...is just calling `pl.savefig(filename)` right after calling with `show=False` not working for you? You should (I think) be able to just call `pl.gcf()` right after the plot call if `show=False` was passed.

**Comment by zkurtz** [comment]
At the moment I'm getting bizarre behavior regardless of which version I use - I have not been able to get your method to work, but may follow up later. Regardless, one argument in favor of passing back the figure explicitly is that the recipient need not have imported `pl` to access and use it.

**Comment by slundberg** [comment]
I think I buy that. However I apologize that a recent refactor means that the update now needs to go in `plots/summary.py`. I am happy to copy it over there it if you prefer, but if you copy it over then github will correctly record you as the author.

**Comment by zkurtz** [comment]
Thanks for checking in, but I'm going to pass this back to you as I don't think the solution I proposed is ultimately satisfactory. In the context of a notebook, I'm observing that the plot gets displayed regardless of whether show = True or False. Specifically, deleting every `pl.show()` command seems to have no effect in a notebook. (It works as expected, on the other hand, in a regular non-interactive script). I'm wondering if it's necessary to define a `fig` variable at the outset of creating the plot rather than picking it up at the last minute (as `pl.gcf()`) to really get full control.

**Comment by slundberg** [comment]
Okay. If you end up with a solution let us know :)

**Pull request closed without merging**
