### PR TITLE
notebook: replace Boston datasets

### PR DESCRIPTION
**Pull request by znacer**
## Overview

Closes related task in #3036 and #2322

Description of the changes proposed in this pull request:
- Replace Boston datasets calls that are deprecated by California.
- Reformat notebooks that are outdated or unclear.

notebook list:
  - [x] notebooks/tabular_examples/model_agnostic/Simple Boston Demo.ipynb
  - [x] notebooks/tabular_examples/tree_based_models/Catboost tutorial.ipynb
  - [x] notebooks/tabular_examples/tree_based_models/Example of loading a custom tree model into SHAP.ipynb
  - [x] notebooks/tabular_examples/tree_based_models/Python Version of Tree SHAP.ipynb
  - [x] notebooks/tabular_examples/tree_based_models/Force Plot Colors.ipynb
  - [x] notebooks/tabular_examples/tree_based_models/Front page example (XGBoost).ipynb
  - [x] notebooks/benchmarks/tabular/Tabular Prediction Benchmark Demo.ipynb
  - [x] notebooks/benchmarks/tabular/Benchmark XGBoost explanations.ipynb

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.

### CODE REVIEW

**Comment by thatlittleboy** [comment]
hi @znacer , thanks for your contribution! (sorry it took a while to get around to reviewing the PR).
I've just merged in another PR #3214 contributing a change to the Catboost tutorial, do you mind resolving the conflict before I review the rest of your PR?

**Comment by znacer** [comment]
Hi @thatlittleboy 
I will try to resolve this during next week

**Comment by znacer** [comment]
@thatlittleboy merge conflict are resolved.

**Comment by thatlittleboy** [comment]
Unfortunately it seems like while we were trying to implement black/ruff on all of the notebooks, it caused a lot of merge conflicts in this PR. Sorry about that.

Currently the PR contains alot of unwanted changes, probably it would be easiest to ensure that the notebooks you listed in your PR description are compliant with black and ruff first, then reapply all the boston dataset replacements, then resubmit the changes (either with force pushing to this PR or feel free to open another one).

**Comment by znacer** [comment]
Ok ! I will close this PR and make one for each notebook to make it easier to update/review.

**Pull request closed without merging**
