### PR TITLE
Allow deep_pytorch to use cuda models

### PR DESCRIPTION
**Pull request by juliusbierk**
Current version fails using cuda model/data:

```
device = "cuda"
model.to(device)
de = DeepExplainer(model=model, data=torch.zeros(1, n_input).to(device))
print(de.shap_values(torch.randn(10, n_input).to(device)))
```

with the following error:

```
Traceback (most recent call last):
  File "/home/julius/research/rna/endoterm/ml2/play.py", line 45, in <module>
    print(de.shap_values(torch.randn(10, n_input).to(device)))
  File "/usr/local/lib/python3.6/dist-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "/usr/local/lib/python3.6/dist-packages/shap/explainers/deep/deep_pytorch.py", line 175, in shap_values
    phis[l][j] = (torch.from_numpy(sample_phis[l][self.data[l].shape[0]:]) * (X[l][j: j + 1] - self.data[l])).mean(0)
RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor
```

This pull request fixes this, but does not do any smart optimisations to avoid unnecessary gpu/cpu data transfer. Speed-up is still significant though.

### CODE REVIEW

**Comment by juliusbierk** [comment]
Build fail seems unrelated.

**Comment by imatiach-msft** [comment]
@juliusbierk the build failure has been fixed, could you please rebase to latest master?

**Comment by juliusbierk** [comment]
> @juliusbierk the build failure has been fixed, could you please rebase to latest master?

Yep.

**Comment by slundberg** [comment]
Thanks @juliusbierk !

**Pull request merged**
