### PR TITLE
MAINT: Configure Ruff formatter, update ruff config

### PR DESCRIPTION
**Pull request by connortann**
This is a small incremental update to streamline our linting and formatting configuration.

Now that the ruff formatter is released and stable, I think it makes sense to use that rather than black. It simplifies our config, is faster, and supports notebooks natively.

Changes:
- `pre-commit`: Remove `black` in favour of `ruff-format`, and remove `check-json`
- `pyproject.toml`: Update ruff config to current spec, with separate `[tool.ruff.lint]` and `[tool.ruff.format]` sections

Reformatted:
- `notebooks/` : A few trivial changes due to the new linter, mostly just reordering parts of the JSON file. No functional changes, so this doesn't really have to be reviewed in detail IMO.

### CODE REVIEW

**Comment by connortann** [comment]
@CloseChoice , would you perhaps give a review on this? It would be good to ensure you're happy with our precommit and linting configuration.

**Review by CloseChoice — APPROVED** [review]
To be honest, I am pretty unopinionated about linting. It's important that it's there and I have heard a couple of good things about ruff, so I am supportive of this change.

I am still struggling to get this running on my Windows machine, but this is an issue with my local setup, so looks good to me from what I can see.

**Comment by connortann** [comment]
Id be interested to hear what issues you face, not least so we can improve the contributing guide with any extra info that might be needed.

What happens if you run:
```
pre-commit install
pre-commit run --all-files
```

**Comment by CloseChoice** [comment]
> Id be interested to hear what issues you face, not least so we can improve the contributing guide with any extra info that might be needed.
> 
> What happens if you run:
> 
> ```
> pre-commit install
> pre-commit run --all-files
> ```



> pre-commit run --all-files

I guess it has something todo with having 2 Python versions on the same windows machine and not managing them correctly, so not sure if this is really something for our docs. Here is the error 
```
$ pre-commit run --all-files
[INFO] Installing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Tobias Pitters\\.cache\\pre-commit\\repo70hjb17v\\py_env-python3.9\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 101
stdout: (none)
stderr:
    Unable to create process using 'c:\users\tobias pitters\appdata\local\programs\python\python39\python.exe -mpip install .'      
Check the log at C:\Users\Tobias Pitters\.cache\pre-commit\pre-commit.log
(venv3.9) 
```
And this is the message in `pre-commit/pre-commit.log`:

```
### version information

pre-commit version: 3.5.0
git --version: git version 2.40.0.windows.1
sys.version:
    3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
sys.executable: c:\users\tobias pitters\appdata\local\programs\python\python39\python.exe
os.name: nt
sys.platform: win32

### error information

An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Tobias Pitters\\.cache\\pre-commit\\repo70hjb17v\\py_env-python3.9\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 101
stdout: (none)
stderr:
    Unable to create process using 'c:\users\tobias pitters\appdata\local\programs\python\python39\python.exe -mpip install .'

Traceback (most recent call last):
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\main.py", line 414, in main
    return run(args.config, store, args)
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\languages\python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "c:\users\tobias pitters\appdata\local\programs\python\python39\lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Tobias Pitters\\.cache\\pre-commit\\repo70hjb17v\\py_env-python3.9\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 101
stdout: (none)
stderr:
    Unable to create process using 'c:\users\tobias pitters\appdata\local\programs\python\python39\python.exe -mpip install .'
```

**Comment by connortann** [comment]
Ah. That does seem like a tricky environment issue. I'm not sure what to recommend other than creating a fresh virtual environment.

I would ensure you run `pre-commit install` from within the same virtual env that you use for the project, whether that be conda, pyenv, venv or similar.

**Pull request merged**
