### PR TITLE
add return figure for summary_plot

### PR DESCRIPTION
**Pull request by AlKul**
## Overview

Closes #XXXX  

Description of the changes proposed in this pull request:

## Checklist

- [ ] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Comment by CloseChoice** [comment]
Thanks for the PR. Could you please elaborate a bit what is your intention behind this? So stating your problem with the current implementation would be great for us, so that we have something to put in the release notes later on. 
Also at some point we would need to fix the tests.

Another thing that makes me a bit curious is that we plan to deprecate this function. Do you still actively use it?

**Comment by AlKul** [comment]
> Thanks for the PR. Could you please elaborate a bit what is your intention behind this? So stating your problem with the current implementation would be great for us, so that we have something to put in the release notes later on. Also at some point we would need to fix the tests.
> 
> Another thing that makes me a bit curious is that we plan to deprecate this function. Do you still actively use it?

Hey!
Thanks for quick reply, actually, that was supposed to be pushed to my fork - my bad

And yeah, I’m trying to use this function right now, for analyzing the importance of features for my multi class classification model

I want the plot function return figure - not just plot it (for saving results for each experiment)

And thanks for the lib - just starting using it, looks useful and interesting

**Comment by CloseChoice** [comment]
Thanks for your work and the reply. I think this is a totally understandable undertaking. Are you still working on this? If so, would be great if you could fix the tests, then I think we are pretty close to merging.

**Comment by connortann** [comment]
Similar functionality implemented by #3561

**Pull request closed without merging**
