### PR TITLE
Fix Install dependencies stage in tests pipeline

### PR DESCRIPTION
**Pull request by alexander-pv**
Hi, I noticed that the test pipleine fails before running pytest because of dependency issues.
This PR is aimed to fix dependency conflicts for all python versions in `run_tests.yml`.

### CODE REVIEW

**Comment by alexander-pv** [comment]
It looks like `test_heatmap.py` contains outdated tests. I think that it may be also a dependency issue 🤔.

**Comment by thatlittleboy** [comment]
Hi @alexander-pv , I'm currently maintaining a fork over at dsgibbons/shap, and making a similar change to `setup.py` at the moment (dsgibbons#32). Just curious, why you went for manually specifying the numpy versions rather than relying on `oldest-supported-numpy` in the build dependency? (if you can still recall the reason why 😅)

**Comment by alexander-pv** [comment]
Hi, @thatlittleboy, as far as I remember there was an issue in the "Install dependencies" step in tests. I think I got stuck with it at that time and for some reason I couldn’t fix it with `oldest-supported-numpy`.
Thanks for your work! That's great to see that this `shap` fork is actively maintained!  I will be glad to contribute at least with further `causalml` library support.

**Comment by thatlittleboy** [comment]
@alexander-pv  Awesome, contributions very welcome. https://github.com/dsgibbons/shap
There's still plenty to do, but I'm positive we'll get there.

**Comment by thatlittleboy** [comment]
Duplicated by https://github.com/slundberg/shap/pull/2943

**Pull request closed without merging**
