### PR TITLE
add new BalancedRandomForestClassifier model

### PR DESCRIPTION
**Pull request by jpzhangvincent**
BalancedRandomForestClassifier is from the imbalanced-learn package. It seems that it just basically inherits from the RandomForest Classifier. I had tested on my use case and didn't have conflicts. Let me know if there are any caveats.

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks! Would you mind also including a quick unit test in test_tree.py? That way we can make sure nothing breaks in the future.

**Comment by jlevy44** [comment]
I second this. Is there anything I can do to help move this forward?!?

Looking to use this model ASAP.

**Comment by jlevy44** [comment]
I cloned this branch, for some reason I am not getting a violin/dot plot:
```
shap.summary_plot(shap_values, X_test)
```
download
How out of date is your branch? @jpzhangvincent  I noticed it is 53 commits behind, is that why?

**Comment by jlevy44** [comment]
I'm using the tree explainer on your branch with balanced RF

**Comment by jlevy44** [comment]
Nevermind, I figured it out. Just converted list to np.array

**Comment by jlevy44** [comment]
All is good on my end. We should merge this!

**Pull request merged**
