### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by meyerson**
small typo is breaking _waterfall.py

### CODE REVIEW

**Comment by watson-sam** [comment]
Please can we get this merged as its incredibly annoying 😩😂

**Comment by bwieciech** [comment]
@watson-sam could you please review / merge this please?

**Comment by watson-sam** [comment]
I would love to and would have already done it but I dont have write access! 

image

**Comment by slundberg** [comment]
Thanks for the fix! Sorry I was slow on the review (was out for a while after paternity leave). I decided to go with another suggestion of switching to `plt` since it is a bit more standard

**Pull request merged**
