### PR TITLE
ENH: add dot_size arg to beeswarm

### PR DESCRIPTION
**Pull request by nkasing**
## Overview

Add argument for `dot_size` in beeswarm plot

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Comment by thatlittleboy** [comment]
Hi @noah-asing , thanks for the interest in contributing to `shap`! Can you elaborate a little more about your use case (e.g. why is a fixed dot size of 16 not sufficient for you)? If possible, please also provide images of the current beeswarm that you are getting so we can also understand the issue at hand.

With plotting wrappers (like our `shap.plots.xxx` functions), I understand that there will always be customizations that users will require, but on our end I also wish to control the number of arguments that we expose. Or at least ensure that each new one we add in has a use-case that is well-documented (e.g. as an issue or in PRs like these).

**Comment by nkasing** [comment]
Hi @thatlittleboy, there isn't a specific "need" per se, more of a "nice to have".

I thought it might be nice to have more definition in the beeswarm to try to visually separate NaN clusters, high-feature-value clusters and low-feature-value clusters. Reducing the `alpha` value resulted in the NaN clusters essentially disappearing completely underneath purple blobs, and I was hoping reducing the dot size might do the trick.

I saw that the `scatter` plots had a `dot_size` arg, so I didn't think there'd be a reason not to add `dot_size` to the beeswarm.

I didn't really think about controlling exposed arguments, so as of now this PR isn't really necessary (feel free to close).

**Comment by thatlittleboy** [comment]
@noah-asing

> I thought it might be nice to have more definition in the beeswarm to try to visually separate NaN clusters, high-feature-value clusters and low-feature-value clusters. Reducing the alpha value resulted in the NaN clusters essentially disappearing completely underneath purple blobs and I was hoping reducing the dot size might do the trick.

Did it make it better?

---

I'm definitely open to adding the customization option, I'll leave this up for a while longer, if anyone else is interested in this functionality feel free to state your use case!

Thanks for the contribution in any case! :)

**Comment by connortann** [comment]
I shall close this for now as we are thinking of implementing style customisation in a different manner: https://github.com/shap/shap/pull/3377

However, thank you for the PR in any case, as it's helpful to understand what features you need! We'll aim to get a proper customisation API implemented, and any and all contributions are highly appreciated.

**Pull request closed without merging**
