### PR TITLE
Remove restriction on numpy version

### PR DESCRIPTION
**Pull request by rmehyde**
This PR removes the restrictions on Numpy versions. Per discussions in PRs #2573 and #2569 as well as issue #2571, numba and numpy dependency synchronization should come from upstream rather than this library.

@imatiach-msft please let me know whether this meets your expectations and approve test workflows if so. Thanks!

### CODE REVIEW

**Review by imatiach-msft — APPROVED** [review]
LGTM!

**Comment by rmehyde** [comment]
Awesome, thanks so much @imatiach-msft! Please let me know if there are any further steps needed from me for merge and release.

Not sure if there's a regular process but it looks like the master branch is continuously updated and releases are cut from it every few months? I'd love to be able to use the newer numpy and numba versions soon. Thanks again!

**Comment by imatiach-msft** [comment]
@rmehyde yes, @slundberg is the author of shap and will approve and merge the PR when ready, but the PR looks good to me.  Yes, shap package is released every couple of months to pypi.

**Comment by rmehyde** [comment]
Makes sense, thanks again for all the help @imatiach-msft!

**Comment by slundberg** [comment]
Thanks @rmehyde! This was a hack because at one point without it a simple pipit install would fail. Happy to remove it now once the tests finish.

**Pull request merged**
