### PR TITLE
Refactor (isort, black)

### PR DESCRIPTION
**Pull request by alexisdrakopoulos**
# Refactoring Coding Style (Black/Isort)

What do we think about starting to use tools such as [black](https://github.com/psf/black) and [isort](https://github.com/PyCQA/isort) for readability/maintainability purposes?

I think this is a good part of our first steps towards a more maintainable code base that follows modern pythonic standards.

## What this PR contains
- I ran `isort .` on the codebase
- I ran `black shap tests` on the codebase
- I added static checkers on our CICD pipeline to check that the `shap` and `tests` directories are compliant

## 18 thousand changes? why?....

I'm looking to open a PR that adds static typing to help make SHAP a little more robust, however tasks like that would be easier if we had a standardised code style (enforced by tools such as black and isort).

Pros:
- Standardised code style that's become quite pythonic in recent years (almost everyone uses black)
- Cleaner/More readable code/imports

Cons:
- Annoying to current devs who would have painful merge conflicts

## What current PR owners should do INSTEAD of merging

run the following on their code base:
```
isort .
black shap tests
```
This would reduce merge conflicts significantly.

### CODE REVIEW

**Comment by alexisdrakopoulos** [comment]
@slundberg what do you think about this? I'd like to start working on static type checking and some more refactoring such as moving from pip to poetry and perhaps adding a docker container.

**Comment by slundberg** [comment]
Let me think on this one a bit. It does create a ton of changes, and also adds a new step for any dev work.

**Comment by alexisdrakopoulos** [comment]
> Let me think on this one a bit. It does create a ton of changes, and also adds a new step for any dev work.
One thing that we can do is help devs with their workflows. I'm thinking we can do things like
- switch to Poetry with frozen dependencies (lock file)
- potentially add a make file to help devs run tests
- a dev guide

**Comment by connortann** [comment]
Glad to say the repo now uses autoformatter (`ruff`). So, closing this as a duplicate.

**Pull request closed without merging**
