### PR TITLE
ENH: minor fix in documentation

### PR DESCRIPTION
**Pull request by MadsJensen**
Old feature_perturbation option mentioned in the function doc string.

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks, sorry for being slow I have been out sick. The doc fix seems great, but there are also tons of formatting changes that if you want to propose them should be part of a separate PR I think. Could just restrict this one to the doc fix? Thanks again!

**Comment by MadsJensen** [comment]
No problem. I hope you are feeling better and it is nothing seriously. 

I'd be happy to combine several doc string changes in this PR or another PR. Should I just go through the functions etc I use or do you have something particular in mind?

**Comment by slundberg** [comment]
If you could just restrict this PR to the doc string changes that would be best, then you can open another one if you want to suggest a bunch of formatting changes. I want to keep them separate if possible :)

**Comment by candalfigomoro** [comment]
Fixed (along with another param) in PR https://github.com/slundberg/shap/pull/1306

**Comment by thatlittleboy** [comment]
Closing in favour of https://github.com/slundberg/shap/pull/3006 since this PR is now stale.

**Pull request closed without merging**
