### PR TITLE
#2806 waterfall color customisation

### PR DESCRIPTION
**Pull request by surbhi-gupta-drishya**

### CODE REVIEW

**Comment by surbhi-gupta-drishya** [comment]
@slundberg  When the PR is approved the users of shap library can change the waterfall plot color as per their wish/requirement. 
Earlier they can see waterfall plot in Red and Blue color only: 
image

Now, they can either use default settings:
image
image

Or, decide colors:
Below is the example of usage: 
image
image

**Comment by surbhi-gupta-drishya** [comment]
Hi @slundberg, 
Please review the changes and accept PR.

**Comment by CloseChoice** [comment]
This is also addresses the issue #3266

**Comment by thatlittleboy** [comment]
I think this PR has already been superseded by #3788 . Will close this, thank you for your contribution regardless!

**Pull request closed without merging**
