### PR TITLE
resolve deprecated obj2sctype in numpy 2.0

### PR DESCRIPTION
**Pull request by paulbkoch**
## Overview

Description of the changes proposed in this pull request:

Resolves the error:

AttributeError: `np.obj2sctype` was removed in the NumPy 2.0 release. Use `np.dtype(obj).type` instead.

### CODE REVIEW

**Comment by CloseChoice** [comment]
Thanks for the PR and great that you found this. Will merge if our pipelines succeed

**Comment by connortann** [comment]
Thanks for the PR! I have merged the master branch into your feature branch; the CI should hopefully pass now.

I was initially surprised that this issue was not picked up by the `NPY201` linting rule that picks up deprecated functions; but, I realise we have explicitly excluded this `_colorconv.py` from linting as it is vendored code. So, thanks for spotting this.

**Review by connortann — APPROVED** [review]

**Comment by jonathanng** [comment]
Anyone else seeing this error now?

```
/shap/plots/colors/_colorconv.py:819: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if np.issubdtype(dtype_in, np.dtype(dtype).type):
```

**Comment by jonathanng** [comment]
I'm using numpy==1.26.4.

**Comment by connortann** [comment]
@jonathanng thanks for the bug report! That looks like a separate issue, so let's track that over at #3782

**Pull request merged**
