### PR TITLE
Support returning the actual matplotlib Figure

### PR DESCRIPTION
**Pull request by richarddli**
## Overview

I'm using SHAP in software (as opposed to a Jupyter notebook). One use case I would like to do is display the SHAP bar chart from an Explanation object. With Force plots, there is an HTML method that returns raw HTML. I've implemented a simple alternative to adding the HTML method everywhere.

In essence, if show=False, return the actual current matplotlib Figure. This means that the calling function can then manipulate the actual figure. This approach also means that a lot of the styling / color options that are part of the library can be made directly on the Figure itself, instead of passing through to the actual plot.

If this approach is acceptable, I'd suggest modifying all the other plot functions as well to behave similarly.

Please let me know your thoughts! cc @CloseChoice

### CODE REVIEW

**Comment by JSchoeck** [comment]
I wanted to make quite the same PR, as for example shap.plots.scatter does currently not return anything, even if show=False.

Definitely should be fixed and harmonized across the different plot types.
Some return nothing, others a plt.Figure, others a plt.Axes.

**Comment by CloseChoice** [comment]
Shouldn't calling `pl.cfg()` outside of calling `bar` return the same figure? E.g.

```python
import xgboost
import matplotlib.pyplot as plt
import shap

# train XGBoost model
X, y = shap.datasets.adult(n_points=1000)
model = xgboost.XGBClassifier().fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

shap.plots.bar(shap_values, show=False)
fig = plt.gcf()
fig.savefig('shap_bar_plot.png')
```
This still gives me the same figure as expected.
Hmm, at beeswarm we return the axis, often we do not return anything. Actually I do not really see an upgrade in this, especially with `show=False` might not be really intuitive.

Edit: @JSchoeck I totally agree that this should be harmonized and the solution provided by @richarddli might be a generally applicable but that needs to be discussed if it is viable for all plots. @connortann what do you think about this?

**Comment by richarddli** [comment]
The Jupyter notebook implementation that I'm using in VSCode automatically invokes `pl.show()` which clears the figure before I can save it. You can argue whether or not that the VSCode behavior is correct, but I see no downside to being explicit about the semantics.

I would also suggest that this approach seems like a much cleaner separation of concerns than something like https://github.com/shap/shap/blob/5768d114eb3ae34081ff61b67f352067b59b6aba/shap/plots/_force.py#L508. `_force.py` in particular takes a bunch of args that it passes to `matplotlib` such as `figsize`. I think having each plot return a matplotlib figure (or equiv), and then a separate set of functions (if desired) to manipulate these figures, is a much cleaner implementation.

**Review by CloseChoice — APPROVED** [review]
Also do not see a downside to this and if this helps users, then it's fine for me.

**Comment by connortann** [comment]
Thanks for the PR! This is a good step towards #3411

**Review by connortann — APPROVED** [review]

**Pull request merged**
