### PR TITLE
DOCS: Enable pre-commit checks for notebooks

### PR DESCRIPTION
**Pull request by connortann**
## Overview

Adds two setsof pre-commit checks to run on notebooks.

1) A basic set of checks, that will run on all the notebooks:

- `check-json` to ensure ipynb files are valid JSON
- `nbqa ruff`, initially with a restricted subset of linting rules

2) A more stringent set of checks for notebooks which have been brought up to scratch:

- `nbqa ruff` with the same set of Ruff rules that are applied to the python package
- `black` formatting

This PR also fixes up some small logical errors in a handful of notebooks to get these two hooks passing, and applies `black` to two example notebooks as a starting point to illustrate the second group of pre-commit checks.

Related: #3074, #3036

## Discussion

It would be helpful to enable precommit hooks to help us review PRs relating to documentation. A lot of notebooks are in a messy state, so it's not possible to enable many linting rules without causing a really large diff. So, this PR is intended as a good starting point that we can build on over time.

I envisage that as each notebook is tidied up and brought up to scratch, we can add it to the list of checks in the second group of precommit checks above. This gives us a way to track which notebooks are clean, and ensure that cleaned notebooks are easily "locked-in" to a tidy state.

Related: submitted a PR to ensure that notebooks are picked up by default by the check-json pre commit hook:
https://github.com/pre-commit/identify/pull/401

### CODE REVIEW

**Comment by connortann** [comment]
@thatlittleboy do you have any thoughts on what hooks we should start with?

This is still a draft, as I haven't run the hooks on the existing files (yet).

**Comment by thatlittleboy** [comment]
> @thatlittleboy do you have any thoughts on what hooks we should start with?
> 
> This is still a draft, as I haven't run the hooks on the existing files (yet).

I think the two you have at the moment are sufficient, I also had `black` over at #3074, plus a couple more like checking the watermark and ruff linting, but I think those can come later along with #3074.

> This PR will inevitably lead to a large bulk-update of all notebooks

We also have the option to *not* run on all the notebooks in this PR, no?

**Comment by connortann** [comment]
> We also have the option to not run on all the notebooks in this PR, no?

I don't think that's possible: our CI configuration mandates that all pre-commit hooks must pass on all files.

I've updated this PR to be a better starting point, just checking that Ruff passes. EDIT: updated description above with current proposal.

**Comment by owenlamont** [comment]
I don't think you need the nbQA pre-commit anymore (I have gone down that path before) as [ruff now supports running on Jupyter notebooks](https://beta.ruff.rs/docs/usage/#pre-commit) just by tweaking some of its pre-commit CLI options. Likewise, its likely unnecessary to add Black, as the[ ruff formatter is nearly at feature parity with Black](https://github.com/astral-sh/ruff/issues/5828) (this is being very actively worked on) and soon hopefully will be.

**Comment by owenlamont** [comment]
I recently updated ruff and added the auto-fix option in [PR-3208](https://github.com/shap/shap/pull/3208). There was no current issues with the Python modules but if that causes too much pain with the notebooks in this PR feel free to remove that auto fix option.

**Comment by connortann** [comment]
> I don't think you need the nbQA pre-commit anymore (I have gone down that path before) as [ruff now supports running on Jupyter notebooks](https://beta.ruff.rs/docs/usage/#pre-commit) just by tweaking some of its pre-commit CLI options. Likewise, its likely unnecessary to add Black, as the[ ruff formatter is nearly at feature parity with Black](https://github.com/astral-sh/ruff/issues/5828) (this is being very actively worked on) and soon hopefully will be.

It's great to see that ruff can run on notebooks directly. I'll take a look and use that rather than indirectly via nbqa.

Ruff's formatter doesn't seem to be released yet, so to start with I'd advocate with sticking with `black` which is a very mature project. It should be straightforward to switch to ruff's formatter in future, should we so desire.

**Comment by connortann** [comment]
As a reminder to myself for later, here's the blog post announcing stable Jupyter support in Ruff:
<https://astral.sh/blog/ruff-v0.0.285>

**Comment by owenlamont** [comment]
Hi @connortann - I didn't realise the Rust formatter hadn't been released yet. That's fine then - if we can implement this without needing nbQA that'd be great. I definitely would like Black included in that case.

**Review by thatlittleboy — APPROVED** [review]
Approving in-principle, I'll leave you to merge when you are ready @connortann 

nicholas-cage-letsgo

**Comment by connortann** [comment]
Thanks @thatlittleboy . I added some better comments, and simplified the pre-commit config as best I could.

In future, we could aim to run `ruff` just once on all files. For now though, I think a second run of Ruff with an "opt-in" selection of cleaned notebooks is the simplest way to go.

One subtlety I noticed is that Ruff's `include` and `exclude` configuration options are ignored when running with pre-commit. So, we must put the selection of files to include or exclude in `.pre-commit-config.yaml`, not in `pyproject.toml`.

**Pull request merged**
