### PR TITLE
add support for GPBoost

### PR DESCRIPTION
**Pull request by fabsig**
GPBoost is a library for combining tree-boosting with mixed effects and Gaussian process models (see https://github.com/fabsig/GPBoost). The tree boosting part is handled by a clone of LightGBM. I.e., GPBoost can be handled in shap in exactly the same way as LightGBM.

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks! This looks good. Can you also add test like the current one for LightGBM ...just to make sure things work and stay working :)

https://github.com/slundberg/shap/blob/cad1019a9887d4e3373a25ad472d839fc49bc377/tests/explainers/test_tree.py#L369-L389

**Comment by fabsig** [comment]
Many thanks for your quick answer! I added a test for GPBoost.

**Comment by fabsig** [comment]
Any updates on this? If it is OK, by when can this be integrated in to shap?

**Comment by slundberg** [comment]
Thanks again, and sorry for the delay! I have been working on a new API for SHAP (while staying backward compatible), and so merging has been slower. This looks good now.

**Comment by fabsig** [comment]
Perfect. Thanks a lot!

**Pull request merged**
