### PR TITLE
fixed linear shap explainer shape for classifiers to be list of ndarray

### PR DESCRIPTION
**Pull request by imatiach-msft**
follow-up to discussion on https://github.com/slundberg/shap/pull/645 , specifically:
https://github.com/slundberg/shap/pull/645#discussion_r293589975 
was the workaround needed for anything in particular?  I validated the tests pass with the multi-class workaround removed.

### CODE REVIEW

**Comment by slundberg** [comment]
I'll need to look more at this. I think it was for some sklearn models that one would think are single class but are stored with a single dimension that makes it look like a multi-class output (with one class).

**Comment by imatiach-msft** [comment]
@slundberg ah, yes, in some cases we have binary classifiers with only one output, and in very rare cases we can have a multiclass classifier with one class (which scikit learn just fails for in their classifiers).  Either could create this 2D coef, but I was mostly concerned about the output of the shap values being an ndarray instead of a list of ndarray, since the difference between the classifier and regressor in our contract is that classifiers output a list.  There is another issue where binary classifiers should really have a 2D coef array with two classes instead of one.
That's exactly what happens with logistic regression in scikit learn:
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
It stores the coefficients as a 2D list of one class in binary case, eg as an example:
[[0.2, 0.4, -0.1, 0.7]]

**Comment by slundberg** [comment]
Makes sense. If this is critical to merge soon let me know. Otherwise I'll snooze this for a few weeks until I have some solid time to consider the implications for current usage. Thanks!

**Comment by imatiach-msft** [comment]
not critical at all, thanks!

**Pull request closed without merging**
