### PR TITLE
Notebook: Tabular prediction Benchmark

### PR DESCRIPTION
**Pull request by znacer**
## Overview

Closes related task in #3036 and #2322

Description of the changes proposed in this pull:   
Replace Boston datasets calls that are deprecated by California.

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.

### CODE REVIEW

**Comment by thatlittleboy** [comment]
Seems like the legend and axis labels are missing from the plots now (compare to the notebook on master)

image

v.s. on master

image

**Comment by znacer** [comment]
calculation of auc seems to be made differently than at the time the notebook was created. I will try to work on it within the next few days.

**Comment by znacer** [comment]
@thatlittleboy auc score has been added to figures :smiley:

**Review by thatlittleboy — APPROVED** [review]
thanks!

**Pull request merged**
