### PR TITLE
Revamp the "Explaining a simple OR function" notebook

### PR DESCRIPTION
**Pull request by thatlittleboy**
## Overview

Description of the changes proposed in this pull request:
* Update the code in the `"Explaining a simple OR function"` notebook with the latest `Explanation` API, in an attempt to encourage the community to use this instead of the old `.shap_values()` API.
* Replaced the usage of the deprecated `feature_dependence` -> `feature_perturbation` param of the `TreeExplainer`.
* Added waterfall plots to bring across the learning point of the notebook more effectively
* Run `black`, `ruff` via `nbqa`, and also `nb-clean` to clean notebook metadata in an attempt to minimize git conflicts.
* Fixed some spelling and grammatical errors

This PR also serves as an example PR for those who wish to contribute towards the effort of #3036 .

## Checklist

- [X] Related to #3036 
- [X] All [pre-commit checks](https://pre-commit.com/#install) pass.
- Unit tests added (if fixing a bug or adding a new feature)
- Added entry to `CHANGELOG.md` (if changes will affect users)

### CODE REVIEW

**Comment by connortann** [comment]
This is a really nice PR, and I highly appreciate the wider effort you describe in #3036 . As this will be an example notebook, now's a good opportunity to discuss what the repo's Jupyter guidelines should be.

Are there any other Jupyter cleanup / style principles that could be implemented here? Some ideas from me:
- Using sphinx cross-references rather than URLs to refer to docstrings or other notebooks
- Adding a MyST target, to allow notebooks to link between each other
- Using the `watermark` extension for reproducibility
- Using pre-commit hooks as much as possible to enforce consitency in Jupyter things
  - Perhaps black-jupyter
  - Perhaps <https://github.com/roy-ht/pre-commit-jupyter>

For inspiration, I quite like PyMC's [jupyter style guide](https://www.pymc.io/projects/docs/en/stable/contributing/jupyter_style.html)

I would also suggest as part of this PR that the desired Jupyter style is added to CONTRIBUTING.md.

**Comment by thatlittleboy** [comment]
Thanks @connortann , all great suggestions. Agree that this PR needs a little more work if it's going to be the de-facto example to follow for #3036 . How about we do this instead: I'll create a separate PR where we can discuss the guidelines (and document down into CONTRIBUTING.md). Then we can revisit this PR again once we're done.

I don't wish to pollute this PR with "chore" changes.

**Comment by connortann** [comment]
Docs for the PR can be previewed here:

<https://shap--3037.org.readthedocs.build/en/3037/>

**Comment by thatlittleboy** [comment]
@connortann This PR is ready for review again :)

**Review by connortann — APPROVED** [review]
LGTM, nice PR!

**Pull request merged**
