### PR TITLE
Ensure PyTorch Deep Explainer can handle single output models

### PR DESCRIPTION
**Pull request by gabrieltseng**
A fix to #301

### CODE REVIEW

**Comment by slundberg** [comment]
Great!

**Comment by AvantiShri** [comment]
Hi @gabrieltseng @slundberg,

How stable is the pytorch implementation of DeepExplainer? We're thinking of using it to analyze pytorch models in the Kipoi repository (http://kipoi.org) for a hackathon happened at BDS 2018 right now. @Avsecz

**Comment by gabrieltseng** [comment]
@AvantiShri, it should be fairly stable, but its functionality is limited, mainly because:

1. The multipliers are only calculated on a module level, instead of functions. See here for more information: https://github.com/slundberg/shap/pull/262

2. Only a few operations have been implemented so far. They are all listed at https://github.com/slundberg/shap/blob/master/shap/explainers/deep/deep_pytorch.py#L316

**Comment by AvantiShri** [comment]
Thank you @gabrieltseng - could I trouble you to add `op_handler['Conv1d'] = linear_1d` to the list at https://github.com/slundberg/shap/blob/1e770087279455784329fb98bbae931b0685784e/shap/explainers/deep/deep_pytorch.py#L320-L325 - you already have MaxPool1d and AvgPool1d, so leaving out Conv1d seems unintentional.

**Comment by slundberg** [comment]
@AvantiShri I don't have a 1D model in front of me to verify it works, but if you find adding Conv1d works for you I am happy to merge a one-line PR as soon as the unit tests pass.

**Comment by AvantiShri** [comment]
Thanks Scott, will do if we end up going in that direction.

One feature that I am planning to implement (let me know if I shouldn't) is functionality to generate a set of reference on-the-fly for each input example (rather than having a fixed `self.data` reference for all the examples). This is relevant because we've found that a reference consisting of dinucleotide-shuffled versions of the input sequence works better than a fixed all-zeros or a GC-content-frequency reference. It looks like the current DeepExplainer implementation fixes `data` as an attribute of the class:

https://github.com/slundberg/shap/blob/1e770087279455784329fb98bbae931b0685784e/shap/explainers/deep/deep_tf.py#L105

However, unlike marcoancona/DeepExplain (where the reference is used to precompute static values in the computation graph), in your implementation `self.data` is evidently fed as an input to the computation graph in the form of `joint_input`, so it seems as though it would be fairly straightforward to modify the code to generate a different reference in `joint_input` dynamically for each input:

https://github.com/slundberg/shap/blob/1e770087279455784329fb98bbae931b0685784e/shap/explainers/deep/deep_tf.py#L247-L250

Please let me know if I'm mistaken!

**Comment by slundberg** [comment]
@AvantiShri that would be great! The only issue I can foresee is that `self.expected_value` will no longer be a single number for all the inputs (since each sample will have it's own background distribution). For now I would just leave `self.expected_value` as `None` when there is not a fixed background set, people can easily compute it anyway as the difference between the model prediction and the sum of the attributions.

I am not sure the best way to expose that functionality, but perhaps letting the `data` argument in the constructor be a function that gets the data sample and produces the background set?

**Comment by AvantiShri** [comment]
Yup, that's what I was thinking too (letting the data argument in the constructor be a function that gets the data sample and produces the background set). Ok, great that you don't foresee any dealbreaker issues.

**Pull request merged**
