### PR TITLE
Fix shrinking to -inf and blowing up to inf of mask_aug and eyAdj_aug of KernelExplainer

### PR DESCRIPTION
**Pull request by aaronwtr**
This behavior occurs when the dimensionality of the feature vectors being fed into the KernelExplainer is very large. L1 regularization consequently runs into issues when trying to convert the -inf values to floats. This fixes the issue I ran into myself as well as the following issues most probably: #577 and #1268 .

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks. Can you give a bit more detail on why setting to zero is the right answer here? I can also walk back through the method, but thought I would start by asking your rational :)

**Comment by aaronwtr** [comment]
Hi @slundberg, my reasoning was more practical than based on solid theory but I can share some of my thinking so that we hopefully will be able to figure out what's causing this. 

What I did was trace back to what features the -infs I was encountering pointed and I noticed that these should not be that important for the prediction I was trying to explain. So I wanted to see whether mapping those particular infs to zero would result in an explanation that still did prioritize features important to the prediction and I found that it did. I stopped debugging there since this was sufficient to serve my purpose of using the KernelExplainer but it still feels a bit unsatisfying not understanding what was causing this. 

Some additional notables that might be useful: the feature vectors I'm explaining are pretty large (~3,000 features) and to obtain robust Shapley value approximations I have found that I needed to crank up the nsamples hyperparameter quite a bit (currently at 75,000). My intuition was that the infinities occurred because of one of these two facts but I was not able to identify precisely where and how this would be happening besides finding back the -infs in mask_aug and eyAdj_aug.

Looking forward to your take on why this might be happening.

**Comment by slundberg** [comment]
Thanks! You might also try using the Permutation explainer since it has been optimized more and might scale better.

I could not reproduce the Inf problems (see the code I tried with below). Perhaps it is because I don't have enough RAM to do 75k samples.

```
import xgboost
import shap
import numpy as np

### train XGBoost model
X = np.random.randn(100, 3000)
y = np.random.randn(100)
model = xgboost.XGBRegressor().fit(X, y)

### compute SHAP values
explainer = shap.KernelExplainer(model.predict, X)
shap_values = explainer.shap_values(X[:2], nsamples=15000)
```

**Comment by aaronwtr** [comment]
I was searching myself for particular samples in my dataset where this occurred and couldn't immediately find it as well. I remember that a while back I was trying to obtain a global explanation (explanation dataset of 1000 samples) and then at some sample the process halted with the Inf error. So this issue seems to occur quite sparsely in a very particular scenario in my case. If I run into the issue again down the line I'll report back here. 

Thanks for all your work on this module, it has been crucial to my Master's thesis and I'm sure it is for the ML research community in general as well.

**Pull request closed without merging**
