### PR TITLE
Decision plot

### PR DESCRIPTION
**Pull request by floidgilbert**
Decision plots show how complex models arrive at their predictions (i.e. how models make decisions). See an overview in /notebooks/plots/decision_plot.ipynb. The plot style and parameters follow summary_plot and force_plot. Currently, only a matplotlib version is available (set `matplotlib=True`). 

TODO

- Title style?
- Points at each vertex?
- A D3 version might show feature values and prediction values in tooltips at each vertex.

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks!! I am traveling the next couple days but will take a look as soon as I can.

**Comment by floidgilbert** [comment]
Added/streamlined features and expanded the associated notebook. If anyone read the previous decision plot notebook, please disregard and start with this version. I'm open to suggestions/corrections. Thanks.

**Comment by slundberg** [comment]
Just an update here. I’ll review this on Monday. Thanks again.

**Comment by slundberg** [comment]
I like this as it stands right now. I think with detailed usage some more suggestions will arise, but for now I am going to merge this since it is a new feature. Great job :)

Further improvements can be as new PR's

**Comment by floidgilbert** [comment]
Thanks Scott. Glad it worked out. What are your thoughts on a D3 version? I haven't developed with D3. Worth the effort? Or should we just drop 'matplotlib=True' and leave it as a raster?

**Pull request merged**
