### PR TITLE
Fix for #615

### PR DESCRIPTION
**Pull request by prempiyush**
Changed the second `if` to an `elif`

### CODE REVIEW

**Comment by imatiach-msft** [comment]
@prempiyush this is a great fix, could you please rebase to latest master which fixes the build?  Also, it would be great if you could add a test corresponding to this change, if not that's ok too, I can merge the change once the build is green.

**Comment by prempiyush** [comment]
@imatiach-msft Hi. I have rebased the latest master. Needed to merge it as well to be able to push it.

**Comment by slundberg** [comment]
Thanks!

**Comment by prempiyush** [comment]
@slundberg Thanks for the merge. When do you think this will be available on pypi?

**Comment by slundberg** [comment]
It is on there now :)

**Pull request merged**
