### PR TITLE
#884 add spark in setup.py tests and fix spark issue with additivity check

### PR DESCRIPTION
**Pull request by QuentinAmbard**
Because pyspark wasn't in the test dependencies, the spark unit test was ignored, leading to errors like #884 
This commit add spark as test dependency and fix an issue ignoring check_additivity as it requires to run the prediction, which isn't implemented yet.
(Long term fix is to support the prediction directly with spark, starting a local spark cluster)

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks for working on this! Looks there are still some spark errors, so I'll hold off on merging right now.

**Comment by QuentinAmbard** [comment]
> ERROR Instrumentation: java.lang.IllegalArgumentException: Unsupported class file major version 55

I suspect this is an issue with the java version used in the travis build, spark is still on java8 and this error suggest that the jdk is running on something else, like java11 

@slundberg I'm not super familiar with travis, should I add the following to the .travis.yaml file and try to re-run the build?

```
jdk:
  - openjdk8
```

**Comment by slundberg** [comment]
Thanks! I was trying to figure out why this fails on python 36 and 37 on windows. Do you have thoughts there?

**Comment by QuentinAmbard** [comment]
Making slow progress here...
- It was failing on Ubuntu because we need java8 and not 11, I fixed that
- On windows the winutils lib was missing (required by spark), so I added that too
- Still have an issue on windows with python. For some reason it's looking for ctype under C:\Python27 and is failing, probably because C:\Python27 is 32b and not 64b.

```
File "c:\python36-x64\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
```

I thought adding `$env:PYTHONPATH = "%PYTHON%\Lib;%PYTHON%\DLLs"` in appveyor would solve this issue but there is something else. I'll try again tomorrow, but any idea is welcome!

**Comment by QuentinAmbard** [comment]
@slundberg all good now!
However I had to remove `- PYTHON: "C:\\Python38-x64"`: tensorflow doesn't work with python 3.8, how did you managed to make it works in the other build?

**Comment by slundberg** [comment]
Thanks @QuentinAmbard this is great!! I have been meaning to remove py38 on windows for a while, it was not working on TF1.14 and I need to re-add it once we bump up the version of TF we are testing.

**Pull request merged**
