### PR TITLE
MAINT: Get tests passing with XGBoost 2.0 in test suite

### LINKED ISSUE #3256: ENH: Test against XGBoost 2.0
### Problem Description

The tests are failing with XGBoost 2.0, as per #3254 . A short-term fix could be to just pin the previous version.

This issue however is to get our test suite passing against the latest version, which I think would be a preferable long-term solution:
<https://github.com/dmlc/xgboost/releases/tag/v2.0.0>

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [x] I'd be interested in making a PR to implement this feature

### PR DESCRIPTION
**Pull request by connortann**
Closes #3256

Addressing the breaking changes detailed in:
<https://github.com/dmlc/xgboost/releases/tag/v2.0.0>

### CODE REVIEW

**Comment by connortann** [comment]
It looks like the default tree_method has changed. However, passing `tree_method="exact"` doesn't seem to recover the previous results, so it looks like something else has changed as well.

One solution could be just to re-generate the baseline images. Alternatively, we could consider using a different estimator for these baseline plots that is more reproducible, such as a Linear Regression.

**Comment by CloseChoice** [comment]
I can't reproduce these errors when running the tests locally. The only errors I get are:
```python
ERROR tests/explainers/test_partition.py::test_translation - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
ERROR tests/explainers/test_partition.py::test_translation_auto - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
ERROR tests/explainers/test_partition.py::test_translation_algorithm_arg - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
ERROR tests/explainers/test_partition.py::test_serialization - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
ERROR tests/explainers/test_partition.py::test_serialization_no_model_or_masker - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
ERROR tests/explainers/test_partition.py::test_serialization_custom_model_save - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
```
Do I need access to the huggingface repo to do so?
And why can't I reproduce the failing plot tests?

**Comment by connortann** [comment]
> I can't reproduce these errors when running the tests locally. The only errors I get are:
> 
> ```python
> ERROR tests/explainers/test_partition.py::test_translation - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
> ERROR tests/explainers/test_partition.py::test_translation_auto - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
> ERROR tests/explainers/test_partition.py::test_translation_algorithm_arg - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
> ERROR tests/explainers/test_partition.py::test_serialization - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
> ERROR tests/explainers/test_partition.py::test_serialization_no_model_or_masker - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
> ERROR tests/explainers/test_partition.py::test_serialization_custom_model_save - OSError: mesolitica/finetune-translation-t5-super-super-tiny-standard-bahasa-cased is not a local folder and is not a valid model identifier listed on...
> ```
> 
> Do I need access to the huggingface repo to do so? And why can't I reproduce the failing plot tests?

The HuggingFace issues are unrelated to the XGBoost issue, and were fixed on master by #3286 .

Issue #3256 is focussed on getting the CI tests passing with XGBoost 2.0. If you can't reproduce the issue locally, perhaps try comparing your local environment to the CI environment on this branch to see if the versions of all dependencies are identical.

**Comment by CloseChoice** [comment]
Ok, found the issue, I was using xgboost==1.7.0 :sweat_smile:

I would take this up and just recreate the images. Does this sound fine for you @connortann ?

**Comment by connortann** [comment]
Yes, contributions are most welcome as always! I'd suggest creating your own PR, perhaps taking this as a starting point if you wish.

**Review by CloseChoice — APPROVED** [review]
LGTM, don't know why we need to increase the absolute tolerance but I already stumbled across this.

**Comment by connortann** [comment]
Thanks for the review, and also for helping look into this issue!

After a lot of digging, I found that the XGBoost models from `v1.7` and `v1.0` differed in the `base_score` attribute. If we fix `base_score` to the original default parameter of `0.5`, we can recover pretty much the exact same model regardless of which xgboost model is used, and consequently the shap plots do not change.

I'd prefer to merge this PR rather than #3307 , as the test suite will pass with both xgboost 1 and 2. In any case, thanks again for helping diagnose the xgboost changes. Your recent PRs to shap are highly appreciated, and I hope you stick around as a contributor or perhaps a maintainer.

> LGTM, don't know why we need to increase the absolute tolerance but I already stumbled across this.

This is not too unusual IMO: the test was already fairly flaky and needed a fixed random seed. I think a slightly more generous absolute tolerance is merited.

**Comment by CloseChoice** [comment]
> Thanks for the review, and also for helping look into this issue!
> 
> After a lot of digging, I found that the XGBoost models from `v1.7` and `v1.0` differed in the `base_score` attribute. If we fix `base_score` to the original default parameter of `0.5`, we can recover pretty much the exact same model regardless of which xgboost model is used, and consequently the shap plots do not change.
> 
> I'd prefer to merge this PR rather than #3307 , as the test suite will pass with both xgboost 1 and 2. In any case, thanks again for helping diagnose the xgboost changes. Your recent PRs to shap are highly appreciated, and I hope you stick around as a contributor or perhaps a maintainer.
> 
> > LGTM, don't know why we need to increase the absolute tolerance but I already stumbled across this.
> 
> This is not to unusual IMO: the test was already fairly flaky and needed a fixed random seed. I think a slightly more generous absolute tolerance is merited.

Always a pleasure to help. I am looking forward to sticking around and helping to improve the quality of this repo. And I have to say this at least once: your communication is superb.

**Pull request merged**
