### PR TITLE
Publishing shapjs to npm registry

### PR DESCRIPTION
**Pull request by SachinVarghese**
Code changes related to #1040. Things covered in this PR are

- [x] Visualizers folder to have a separate index file to be imported in commonjs format
- [x] Webpack config update to create to separate targets (in Jupyter notebooks and external projects) 
- [x] Dev dependencies update (Webpack and babel)
- [x] Added a README, updated `package.json`, and `.npmignore` file as required for publish
- [x] Tested the existing build with the `index.html` file
- [x] Added a developer-docs file with a publish script for future updates/releases

### CODE REVIEW

**Comment by SachinVarghese** [comment]
Hi @slundberg I have submitted this PR as discussed at #1040 
Please review and let me know your thoughts. 
Happy to clarify any further questions you have. Thanks

**Comment by SachinVarghese** [comment]
Hello, @slundberg I have noticed that the integration tests have failed. I am not fully sure it is due to the changes in this PR. Could you please review the PR and the tests? Thanks

**Comment by slundberg** [comment]
Thanks! Sorry the review took a while. It looks good to me and the problems are due to some floating type mismatch I think on some windows machines that needs fixed but is separate from this.

**Comment by SachinVarghese** [comment]
@slundberg Thanks for reviewing the updates. The `shapjs package` is now published in npm registry as a public module at https://www.npmjs.com/package/shapjs

Also users can use the plots in external projects as follows
```
import { AdditiveForceVisualizer } from "shapjs";
```

This can be republished again on any further changes by running the script at https://github.com/slundberg/shap/blob/master/javascript/developer-docs.md

**Comment by nehakhands** [comment]
@SachinVarghese @slundberg  I understand its a closed issue. But not sure how do i reach out to you as I have similar requirement as you did but need the waterfall visualisation instead of force visualisation via shapjs.   I understand the additions you have made (AdditiveForceVisualizer and ArrayVisualizer) are specifically for force plot. Could you please give some input on what changes i can make to represent the ML response in waterfall visualization via the npm library? I have also posted the same in the discussions. 

https://github.com/slundberg/shap/discussions/2988

Would appreciate your help. 

Kind Regards
NK

**Pull request merged**
