### PR TITLE
[Minor][Doc] Spelling in README.md

### PR DESCRIPTION
**Pull request by jona-sassenhagen**

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks!

**Comment by jona-sassenhagen** [comment]
Failed CI looks unrelated: `error: numpy 1.16.4 is installed but numpy<1.21,>=1.17 is required by {'numba'}`

**Comment by jona-sassenhagen** [comment]
Uhh green @slundberg

**Comment by jona-sassenhagen** [comment]
Wanna merge?

**Comment by slundberg** [comment]
Hey! Sorry to drop off here, I had a deadline then a baby...so yeah I am back now and working to catch up on stuff :) Thanks again!

**Comment by jona-sassenhagen** [comment]
Congrats on the baby Scott :)

**Pull request merged**
