### PR TITLE
Enh/3263: PyTorchDeep now also allows to check for additivity (activated by default)

### LINKED ISSUE #3263: ENH: Implement check_additivity for DeepExplainer with pytorch
### Problem Description

Many users are confused by the fact that shapley values sometimes are not adding up to the model output:
- https://github.com/shap/shap/issues/2875
- https://github.com/shap/shap/issues/2204
- https://github.com/shap/shap/issues/2785
- https://github.com/shap/shap/issues/2124
- https://github.com/shap/shap/issues/2765

(Partially) this is due to problems like explained in https://github.com/shap/shap/issues/2124#issuecomment-1719253006, https://github.com/shap/shap/issues/2204#issuecomment-933036857 or https://github.com/shap/shap/issues/2204#issuecomment-1526545669.

Fixing all of that probably is not that easy and shap will still be prone to future changes in the `torch` library. It would be nice to see `check_additivity` being implemented for the pytorch DeepExplainer and in case it shows a warning, having a nicely documented help page where users can find out what could actually be going on and providing alternate solutions (e.g. using `GradientExplainer` instead, which apparently does the trick for a couple of users).

Right now the variable is [there](https://github.com/shap/shap/blob/96467db542d519495023d735fa35d4855e25be9b/shap/explainers/_deep/deep_pytorch.py#L134), but unused.

The implementation of this check could be inspired by the [implementation](https://github.com/shap/shap/blob/96467db542d519495023d735fa35d4855e25be9b/shap/explainers/_deep/deep_tf.py#L320) in the tensorflow-part.

### Alternative Solutions

_No response_

### Additional Context

_No response_

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [x] I'd be interested in making a PR to implement this feature

### PR DESCRIPTION
**Pull request by noxthot**
## Overview

Closes #3263 

Description of the changes proposed in this pull request:
- PyTorchDeep now also allows to check for additivity (sum of shapley values should equal model output)
- Activate this check by default

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Comment by connortann** [comment]
Thanks for the PR, this looks like a good change!

I think we should consider where the best place to make this check is. In an ideal world, we would have sufficient unit tests checking for additivity that that this check never fails at run time. However, that's probably not realistic as we can't account for every possible input model.

Regarding default values, it looks like the default is actually defined in the the `DeepExplainer` class, and the defaults in `PyTorchDeep` have no effect (I think). In any case, it looks like the parameter was previously "True" by default, but had no effect in Pytorch.

May I suggest adding a unit test in `test_deep.py` to run this additivity check on an example model(s)?

**Comment by noxthot** [comment]
Thanks for your fast feedback.

> I think we should consider where the best place to make this check is. In an ideal world, we would have sufficient unit tests checking for additivity that that this check never fails at run time. However, that's probably not realistic as we can't account for every possible input model.

I agree that this should not fail in runtime, but I am afraid that this check makes sense during runtime because:
- we can not account for every possible change and/or new feature in `torch` library
- problems like this: https://github.com/shap/shap/issues/2204#issuecomment-933036857

> Regarding default values, it looks like the default is actually defined in the the `DeepExplainer` class, and the defaults in `PyTorchDeep` have no effect (I think).

I guess you are right because this seems to be the usual entry point:
```
e = shap.DeepExplainer(...)
shap_values = e.shap_values(...)
```
but as far as I understand, you could also execute
```
shap_values = e.explainer.shap_values(...)
```
where it would take the default values within the `PyTorchDeep` or `TFDeep`. Imho it's better to have a single point of defining defaults for optional values to avoid confusion and ease maintenance and it seems like `__init__.py` is a good place for defining the defaults.

> In any case, it looks like the parameter was previously "True" by default, but had no effect in Pytorch.

Agreed

> May I suggest adding a unit test in `test_deep.py` to run this additivity check on an example model(s)?

Not sure if I understand correctly, but the additivity check is done by default due to the `check_additivity = True` by default and the tests are already covering the `shap_values()` method (which then also calls `check_additivity`).

**Comment by connortann** [comment]
> tests are already covering the shap_values() method (which then also calls check_additivity).

Ah, indeed you are right. Well then, I think this PR is good to go!

(Apologies for the delayed response, I'm traveling this week)

**Review by connortann — APPROVED** [review]
LGTM, thanks again for the PR.

**Comment by noxthot** [comment]
Thanks. I unfortunately just found a bug moments after you merged the request -> #3280

**Pull request merged**
