### PR TITLE
Migrate to a src layout

### LINKED ISSUE #3020: CI: unit tests should run against a full install, not an editable install
### Issue Description

The CI unit tests do not test the built library; they use a local "editable" install. This means that problems with the build/packaging are likely to be missed. This is concerning, as it could lead us to unknowingly publish a broken wheel.

Issue https://github.com/slundberg/shap/issues/3012 is an example of this: the tests pass on CI, but fail when running with cibuildwheel. This change aims to prevent that happening in future.

Another recent example is #3021 - a packaging error was inadvertently introduced in a previous PR, which broke the wheels and was not caught on CI.

Related #2979

### Ensuring the correct library is picked up

The fix is not as simple as removing the `--editable` flag from `pip install`, as the wrong library can be imported on sys.path. The library is installed to `/lib/python3.11/site-packages`, but when shap is imported the library incorrectly imported from the current working directory `/home/runner/work/shap/shap/shap/__init__.py`. More info in this recent [CI run](https://github.com/slundberg/shap/actions/runs/5337284077/jobs/9673122016?pr=3017#step:6:68) .

A quick fix is to replace `python -m pytest` with `pytest`, as that avoids adding the current working directory to sys.path. However, this is not particularly robust.

A full fix would be migrating to a `src/` layout. From the [pytest docs](https://docs.pytest.org/en/7.2.x/explanation/goodpractices.html#tests-outside-application-code):

> Generally, but especially if you use the default import mode prepend, it is **strongly suggested** to use a src layout. Here, your application root package resides in a sub-directory of your root, i.e. src/mypkg/ instead of mypkg.
> 
> This layout prevents a lot of common pitfalls and has many benefits, which are better explained in this excellent [blog post](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure%3E) by Ionel Cristian Mărieș.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### PR DESCRIPTION
**Pull request by connortann**
## Overview

Closes #3020.

Tentative work-in-progress, exploring migrating to a `/src` layout as explained in issue above.

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Added entry to `CHANGELOG.md` (if changes will affect users)

### CODE REVIEW

**Comment by PrimozGodec** [comment]
I don't like the solution with src since it doesn't look nice (and almost no python modules use it). I think the solution in https://github.com/slundberg/shap/pull/3017#issuecomment-1601613640 would be enough to solve all our problems.

**Comment by connortann** [comment]
The "src" pattern is advocated for rather strongly in the [pytest docs](https://docs.pytest.org/en/7.2.x/explanation/goodpractices.html#tests-outside-application-code). There is a good discussion in the python [packaging guide](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). It's used in several other repos, for example [Streamlit](https://github.com/streamlit/streamlit), [pytest](https://github.com/pytest-dev/pytest), [hypothesis](https://github.com/HypothesisWorks/hypothesis/tree/master) and I'm sure many others.

I think that avoiding nefarious packaging problems is a much higher priority than stylistic neatness, so if the `src` layout leads to more reliable testing and packaging then I think it's at least something worth contemplating.

Personally I don't think it's particularly ugly in any way; but, the big diff in this change is a downside. I'll explore other options as you say, and I suggest we keep this on the backburner for now for consideration.

**Comment by jklaise** [comment]
@connortann you can add a `.git-blame-ignore-revs` file with hashes of commits to ignore when running `git blame` either locally or through the Github UI, it's a good solution for doing things like these and mitigating issues with large diffs when looking back.
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by connortann** [comment]
Yes indeed, in fact that was raised in an earlier thread in https://github.com/slundberg/shap/pull/3006#discussion_r1236752351 .

I'll add this in a future PR, as we have had several style & refactor PRs recently.

EDIT: opened a PR #3027

**Comment by dsgibbons** [comment]
I don't think a `src` layout is ugly. It seems to be the standard when you read about packaging on the Python website anyway. If we think this will prevent problems in the future, then I'm on board with it.

**Comment by connortann** [comment]
Closing as not planned for now, as we have got the testing & packaging working adequately at least for now.

That said, I'd be keen to come back to this if we encounter any more subtle build issues. For example - at present, our test suite in cibuildwheel will fail unless pytest is run with a non-default `import_mode` option... 🫤

**Pull request closed without merging**
