### PR TITLE
Urgent Support, Please!!!!!TypeError: 'NoneType' object cannot be interpreted as an integer

### PR DESCRIPTION
**Pull request by thuybt**
image
I try to run this source code from Shap Source code example, 
And This error occur, please tell me this is something relate to new version updated from tensorflow and Shap (current version) is no longer support it!!!!!!! I am nearly out of my project and really need all of your help
image

### CODE REVIEW

**Comment by alexcoca** [comment]
Can you assign `x_test[:1]` to a variable and print its shape before calling `shap_values`?

**Comment by slundberg** [comment]
Hey, sorry I have been out sick. There are a lot of file changes mixed in here, could you rebase or something to highlight just the changes you are suggestion? Thanks!

**Comment by slundberg** [comment]
I think something needs to rebased here so we don't have tons of unrelated diffs showing up

**Comment by threadgoldc** [comment]
> image
> I try to run this source code from Shap Source code example,
> And This error occur, please tell me this is something relate to new version updated from tensorflow and Shap (current version) is no longer support it!!!!!!! I am nearly out of my project and really need all of your help
> image

hey. Also have the same problem. Has there been any movement on this?

**Comment by pierresphabmixay** [comment]
Same problem here.
I tried using tensorflow v=2.0.0 and v=2.1.0 on it. Neither worked

**Comment by ghost** [comment]
Same problem here as well. I used TF v2.1.0.

**Comment by orionym** [comment]
Same problem...using TF 2.1.0

Any solution?

**Comment by ssemyonov-quantori** [comment]
Anyone found a solution?

**Comment by MislavSag** [comment]
I get same error when applied shap values on LSTM:
```
explainer = shap.DeepExplainer(model, X_train_lstm)
shap_value = explainer.shap_values(X_test_lstm)
```
where X_train_lstm and X_test_lstm are 3D arrays.

**Comment by mawic** [comment]
I get the same error with tf 2.2.0. Any solution yet?

**Comment by slundberg** [comment]
closing this PR since it is not clear what it being added with all the commits. Please feel free to reopen :)

**Pull request closed without merging**
