### PR TITLE
Fix failing CI on python 3.12 due to outdated numba & llvmlite

### PR DESCRIPTION
**Pull request by thatlittleboy**

### CODE REVIEW

**Comment by thatlittleboy** [comment]
Local copy is python 3.12.1, installing from latest master from github (with the failing CI)

image

---

image

**Comment by thatlittleboy** [comment]
Numpy and numba had releases earlier (the CI run from yesterday ran successfully), so it can't be due to these two.


image

Setuptools has had a new release yesterday.

**Comment by connortann** [comment]
This looks like an issue with numba - I believe I encountered it earlier. I'll dig up the relevant PR / issue....

**Comment by connortann** [comment]
@thatlittleboy I think this could be another occurrence of a bug we encountered a few weeks ago: https://github.com/numba/numba/issues/9708#issuecomment-2296824946

## What's the cause?

Modern `numba` releases include an upper bound on numpy. However, older versions of `numba` do not include this upper bound, which can lead a package manager (`uv` in our case) to resolve a much older version of numba, in order to allow a recent version of numpy.

This is erroneous, as the older version of numba is not actually compatible with the latest numpy. That older numba uses a corresponding older version of `llvmlite` which fails to build on python 3.12.

This is not the package manager's fault but rather a fault with incomplete & inconsistent version bounds. For a 10,000 word essay on the problems that upper versions bounds cause in python, this [blog post](https://iscinumpy.dev/post/bound-version-constraints/) makes for interesting reading.

We encountered a similar error previously on #3817, which I fixed in #3818 by increasing the numba lower bound to `0.52`.

## Proposed fix

I think the cleanest fix is to bump the lower bound for numba to `numba>=0.54`, which seems to be the first release which includes the numpy upper bound.  `0.54` was released on 19 August 2021, which is well over the two-year window we should support according to [SPEC 0](https://scientific-python.org/specs/spec-0000/).

**Comment by thatlittleboy** [comment]
hey @connortann thanks for the writeup, feel free to make the relevant fixes, i'll probably only have time to come back to this later during the week; abit busy with work now.

**Comment by connortann** [comment]
OK, I'll push to this branch..

**Review by connortann — APPROVED** [review]
That pin has fixed it. Back over to you @thatlittleboy to approve & merge if you're happy :)

**Pull request merged**
