### PR TITLE
fix travis build due to xgboost install error

### PR DESCRIPTION
**Pull request by imatiach-msft**
using suggestion from here:
https://github.com/dmlc/xgboost/issues/1786
specifically:
https://github.com/dmlc/xgboost/issues/1786#issuecomment-299387401

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks for working on this!! I have been finishing up job stuff and am defending next week so I have been behind on issues.

**Comment by imatiach-msft** [comment]
I found the same error here:
https://forums.synfig.org/t/solved-gomp-4-0-not-found-ubuntu-14-04-derivated-distros-related/9137/3
Which suggested that the issue was that with ubuntu 14.04 gomp 4.0 does not work with the default older version of gcc/g++, at least version 4.9 is required.
This led to the suggestion from here:
https://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu/581497#581497
Which fixed the build.

**Comment by imatiach-msft** [comment]
@slundberg I think this PR is good to merge to master, will merge this tomorrow morning if there are no new comments to unblock other builds for PRs

**Comment by slundberg** [comment]
Thanks again! This was a much needed fix!

**Pull request merged**
