### PR TITLE
fixed Tree.__call__  to support lightgmb: plain DataFrame needs to be passed to predict()

### PR DESCRIPTION
**Pull request by ibobak**
This problem  https://github.com/slundberg/shap/issues/2144
is fixed by my pull request.

### CODE REVIEW

**Comment by ibobak** [comment]
Dear authors of SHAP, I am really not familiar what is appveror and what has failed.  I looked through the logs and really count not understand how this thing is related to what I've included into my pull request.  Seems as this is not related at all.

**Comment by ibobak** [comment]
Dear @slundberg,  could  you please look at what is going on with the automated checks?

**Comment by Npaffen** [comment]
@ibobak Could you quickly explain how I can merge your solution to my existing version of SHAP manually? I'm quite new to python please excuse this possibly very basic question.

EDIT : Answered this question on my own. For all who might be interested :

1) Use  : print(shap.__file__)
2) Copy the printed path until ...shap\
3) Goto folder 'explainer'
4) Open file 'tree_py'
5) Search for 'def __call__'
6) Replace the part stated in #2144

**Comment by seakelle** [comment]
Any updates on this? Would be nice to have this working.

**Comment by thatlittleboy** [comment]
Duplicated by https://github.com/slundberg/shap/pull/2943

**Pull request closed without merging**
