### PR TITLE
refactor: use it.combinations instead of it.combinations_with_replacement

### PR DESCRIPTION
**Pull request by thatlittleboy**
## Overview

Description of the changes proposed in this pull request:

A small follow up from my previous PR #3761, comment by Connor: [LINK](https://github.com/shap/shap/pull/3761#discussion_r1690223340)

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Review by connortann — APPROVED** [review]

**Comment by thatlittleboy** [comment]
@connortann Any idea why this job is now failing on Windows?

https://github.com/shap/shap/actions/runs/10232378534/job/28309628156

I'm not sure why this problem didn't surface in your previous 2 PRs (just merged in) and commits though.

**Comment by connortann** [comment]
Hmm, strange. It looks like it might possibly be related to this issue:
https://github.com/astral-sh/uv/issues/1491

**Comment by thatlittleboy** [comment]
> @connortann Any idea why this job is now failing on Windows?
> 
> https://github.com/shap/shap/actions/runs/10232378534/job/28309628156
> 
> I'm not sure why this problem didn't surface in your previous 2 PRs (just merged in) and commits though.

So it seems that Matplotlib recently deleted their 3.9.1 release wheel for Windows ([source](https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2267225291)) due to a critical bug, so that explains why this problem didn't surface in earlier runs.

And this in turn resulted in matplotlib being built from source via `uv`, and some sort of build error caused it to fail (still unsure what). Strangely though, I tested [here with a debug branch](https://github.com/shap/shap/actions/runs/10236308054/job/28318207052) that using `pip` instead of `uv` to install `matplotlib==3.9.1` (built from source) on windows **doesn't** cause an error.

So the actual fault seems to be a combination of `windows + uv + matplotlib being built from source`..

Regardless, I'm expecting that matplotlib 3.9.2 is going to be released soon (also reiterated by mpl's maintainers), where the wheels will be reintroduced back for windows. I suggest we just wait till then to rerun the CI.

**Comment by connortann** [comment]
Thanks for the analysis!

As a short-term workaround, we could also add a constraint in the test dependencies of `matplotlib!=3.9.1`.

If you have time, it might also be helpful to raise a report with uv to investigate why that install fails on windows with uv. Perhaps the issue could be reproduced with the uv equivalent of:

```bash
pip wheel --no-cache-dir --use-pep517 "matplotlib (==3.9.1)"
```

**Comment by tacaswell** [comment]
The 3.9.1 wheels on windows would, depending on import order, cause segfaults, see https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266699619.

We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel.  We have now yanked the whole 3.9.1 release to fix these problems and will get 3.9.2 out as quick as we can.

To prevent this sort of thing in the future (trying to build something from source when you are not prepared to do so) I suggest using `matplotlib --only-binary "matplotlib" ` in your requirements file (which may be a good practice for all wheels that have extentions).

Sorry for the trouble.


----

As a side note, the install failing with `uv` but "working" with pip may in fact be a bug with pip as some of the other failure reports we got indicated building "worked" and Matplotlib was installed, but the c-extension modules were missing and we failed immediately on import.

**Pull request merged**
