### PR TITLE
fix output of shap TreeExplainer with lightgbm to be list of ndarray in binary case to conform to other explainers and scikit learn output

### PR DESCRIPTION
**Pull request by imatiach-msft**
Fix output of shap TreeExplainer with lightgbm to be list of ndarray in binary case to conform to other explainers and scikit learn output.

Currently SHAP TreeExplainer outputs a single ndarray of shap values for LightGBMClassifier in binary classification case.  However, for scikit-learn models in both binary and multiclass classification the result is always a list of ndarray, one for each class (in binary case there are two ndarrays).  This PR fixes this scenario to conform to the scikit learn API and other shap explainers.  In general, we should expect SHAP to output list of ndarray for classification case and a single ndarray in regression case.

### CODE REVIEW

**Review by slundberg — CHANGES_REQUESTED** [review]
This all looks good to me. But since it is a significant API change would you mind putting in a warning when this is triggered? We can leave that warning in for only one version, but I think flagging the change is important.

Also have you looked at any of the example notebooks that might be effected by this? Just want to make sure we don't break them :)

**Comment by imatiach-msft** [comment]
@slundberg yes, it looks like this notebook broke: "Census income classification with LightGBM"
will update

**Comment by imatiach-msft** [comment]
@slundberg I've updated the notebook, thanks

**Review by slundberg — APPROVED** [review]

**Comment by slundberg** [comment]
Looks great, thanks!

**Pull request merged**
