### PR TITLE
Build macos arm64 wheels

### PR DESCRIPTION
**Pull request by PrimozGodec**
## Overview

Description of the changes proposed in this pull request:

SHAP does not provide arm64 wheels for MacOS, which is essential since most of modern Mac computers use this architecture. With this PR, I am enabling the building of amr64 wheels. 

I would also be very happy if arm64 wheels would be added to PyPi as soon as possible.

I ran the building process on the branch, and it successfully build arm64 wheels: https://github.com/PrimozGodec/shap/actions/runs/5504208255

## Checklist

- [ ] Closes #xxxx  
- [ ] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)
- [ ] Added entry to `CHANGELOG.md` (if changes will affect users)

### CODE REVIEW

**Comment by connortann** [comment]
Thanks for the PR! Yes, it would be great to get a broader range of wheels built. To get last week's release out the door, we took a pragmatic decision last week to build with a relatively restricted set of wheels (mirroring the set chosen in `scikit-learn`), accepting it wasn't as comprehensive as we'd like.

## Patch release

As you mention you're eager to have wheels on PyPI as soon as possible, maybe we can make a patch release `0.42.1` with a broader range of wheels. `linux: aarch64` wheels have also been requested on #3061. What do you think @thatlittleboy ? 

Nb. I'm testing things on a separate branch `maint/add-archs`, to ensure we don't include other changes on `master` that aren't in the release notes.

## Testing on MacOS

One snag I noticed is that cibuildwheel can't currently run tests on arm64:

> While arm64 wheels can be built on x86_64, they cannot be tested. The ability to test the arm64 wheels will be added in a future release of cibuildwheel, once Apple Silicon CI runners are widely available.

I don't know if there's anything we can do about this, so may have to just take the chance. @PrimozGodec , are you by any chance able to run the tests locally on your machine against the wheel on `arm64`?

**Comment by thatlittleboy** [comment]
The way I see it is that for those on arm64 macs, (in the absence of the appropriate CI runners) it's either we release an untested wheel or None at all, and I think the former is a better scenario for us to be in.
It's the same situation with our cuda c extension module actually. 😅

A patch release sounds good. We need one anyway because of #3075.

**Comment by connortann** [comment]
OK, I'll work on a patch release. Created a milestone and a new meta-issue #3082 .

I'll come back to this PR shortly once I've done some related testing :)

**Comment by PrimozGodec** [comment]
@connortann, thank you for taking quick action. 

> I don't know if we can do anything about this, so we may have to just take the chance. @PrimozGodec , are you, by any chance, able to run the tests locally on your machine against the wheel on arm64?

I think we cannot do anything about it. As I know cibuildwheel plans to enable that in the future. Also, numpy/scipy don't test wheels on arm64. I tested the wheel locally, and the tests passed.

>  it's either we release an untested wheel or None at all

I think it is better to provide a wheel and the community report if anything is wrong. Having wheels makes life easier for people without compilers on the computer.

**Review by connortann — APPROVED** [review]
Looks good!

**Pull request merged**
