### PR TITLE
chore: update changelog entries

### PR DESCRIPTION
**Pull request by thatlittleboy**
## Overview

Description of the changes proposed in this pull request:

* Update the changelog to latest commit (f77a5ae5). Somewhat in preparation for the impending release.
* Prepend `dsgibbons` to the PR names in the changelog, so it is clearer which are PRs from the community fork and which are from here.

## Checklist

- [X] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)
- [ ] Added entry to `CHANGELOG.md` (if changes will affect users)

### CODE REVIEW

**Comment by connortann** [comment]
May I suggest adding a "Maintenance" section, as there have been several PRs relating to linting, CI, and build? Example from the pymc changelog: https://github.com/pymc-devs/pymc/releases

**Review by connortann — APPROVED** [review]
LGTM, with suggestions above

**Comment by connortann** [comment]
PS - another suggestion. Scott requested "please be sure to note who contributed in the release notes". Shall we update the changelog with PR author names, perhaps in the same style as pymc above?

**Review by thatlittleboy — COMMENTED** [review]
The changes since last commit:
* Added a maintenance section, and moved the tests/linting/build related PRs there.
* Added authors in the form of (`#PR by @author`), and e.g. the ruff linting one, I grouped all the ones by the same author.

Let me know if you think it's ok or needs more changes. Thanks @connortann

**Review by connortann — APPROVED** [review]

**Pull request merged**
