### PR TITLE
Enabeling to create a beeswarm figure without sum of other features.

### PR DESCRIPTION
**Pull request by kalkairis**
This PR is meant to deal with issue #1984

### CODE REVIEW

**Comment by slundberg** [comment]
Thank you! Sorry I was out for a while and let this PR just sit around. I updated it to mesh with some other PRs and once the tests pass this is good to merge. Thanks again!

**Comment by kalkairis** [comment]
Hi @slundberg , I've tried merging with master and updating the images via `pytest --mpl-generate-path=tests/plots/baseline` and still the tests fail on image errors. If you have any time to try and figure this out w/ me or point me in the right direction to solve this issue I'd really appreciate it :-) 
Thanks!

**Comment by Naoto-Yamaguchi** [comment]
@kalkairis @slundberg 
Thank you for the great modification! I guess this branch has not merged into the master branch yet. I hope this useful change will be merged.
Also, it would be great if you could add the same function to the bar plot.

Thank you in advance!

**Comment by yudeng2015** [comment]
what is the status on this? Is it possible to plot the barplot without showing the last row (sum of other features)? much appreciated!

**Comment by kalkairis** [comment]
> what is the status on this? Is it possible to plot the barplot without showing the last row (sum of other features)? much appreciated!

When creating this PR I tried to make the tests work and failed over and over again. Feel free to try and fix them and push them to this PR.

**Comment by dirkpelt** [comment]
Hi everyone, what's the status on this issue? I am using beeswarm and bar plots and sum of features is included.

**Comment by ghost** [comment]
any update?

**Comment by williamty** [comment]
is this fixed?

**Comment by yudeng2022** [comment]
I ended up using bar plot where you can choose the top features 
https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/bar.html

**Comment by ttpro1995** [comment]
Is this fix update in stable version yet ?

**Review by kalkairis — COMMENTED** [review]
I'll try to get back to it soon.

**Comment by connortann** [comment]
Hi @kalkairis . Thanks for the PR!

Sorry that your PR hasn't been reviewed until now. You might be aware the repo was unmaintained for a while, but now we're back in business with a new [tiny team of maintainers](https://github.com/shap/shap/discussions/3559).

It's taking us time to work through the huge issue and PR backlog, but we're definitely getting there. Thanks for the PR, I'll have a look..

**Review by connortann — APPROVED** [review]
This looks good, thanks again!

I fixed the merge conflicts (as we introduced the `ruff` auto-formatter), and made a few minor housekeeping tweaks:
- Renamed the new parameter to `group_remaining_features`
- Removed changes to baseline images which don't relate to this function
- Added an extra test to show the plot with and without the bottom row

PS - This is probably a record for the longest delay between opening a PR and having it merged. I hope we get PRs sorted much more swiftly in future!

**Comment by tbonewmy** [comment]
can you please enable this argument in all plots that will group remaining features? the bar plot also do this

**Pull request merged**
