### PR TITLE
Interim Explanations for the PyTorch Gradient Explainer

### PR DESCRIPTION
**Pull request by gabrieltseng**
This is a partial solution to #191, and an improvement to #250. I would appreciate any feedback!

Inputs to interim layers can now be explained, by passing a tuple (model, input) as model. If only a model is passed, the inputs to the actual inputs will be explained.
A note about this is that local smoothing is still applied on the actual inputs, as opposed to the inputs of the layer to be explained.

In addition, the Gradient Explainer now autodetects the framework of the model

Finally, I reran the Imagenet notebook with the interim layer, and replaced the MNIST notebook with it.

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks! I am trying to test it out, but not being much of a pytorch user I am not sure how it is meant to work with the GPU. If I just do `.cuda()` after the model and the normalized inputs I get out of memory errors on a GTX 1080. How have you been setting it up for the GPU?

**Comment by gabrieltseng** [comment]
Hi @slundberg,

I had previously only run this on my local machine, and ran into memory errors as well when running it on a GPU. The changes I've made seemed have to fix the issues.

Sorry about that!

**Comment by slundberg** [comment]
Great! I noticed the model must be a bit different than for the TF example we have since the resolution of your explanations looks higher.

Also, I must still be using the cuda stuff on pytorch wrong since when I use the following I no longer get out of memory errors but get another error:

```python
# load the model
model = models.vgg16(pretrained=True).eval().cuda()

X,y = shap.datasets.imagenet50()

X /= 255

to_explain = X[[39, 41]]

# load the ImageNet class names
url = "https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json"
fname = shap.datasets.cache(url)
with open(fname) as f:
    class_names = json.load(f)
e = shap.GradientExplainer((model, model.features[7]), normalize(X).cuda())
shap_values,indexes = e.shap_values(normalize(to_explain).cuda(), ranked_outputs=2, nsamples=2)
```

produces
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-9a595d0ff9b5> in <module>()
     14     class_names = json.load(f)
     15 e = shap.GradientExplainer((model, model.features[7]), normalize(X).cuda())
---> 16 shap_values,indexes = e.shap_values(normalize(to_explain).cuda(), ranked_outputs=2, nsamples=2)
     17 
     18 # get the names for the classes

~/projects/shap/shap/explainers/gradient.py in shap_values(self, X, nsamples, ranked_outputs, output_rank_order)
    106         were chosen as "top".
    107         """
--> 108         return self.explainer.shap_values(X, nsamples, ranked_outputs, output_rank_order)
    109 
    110 

~/projects/shap/shap/explainers/gradient.py in shap_values(self, X, nsamples, ranked_outputs, output_rank_order)
    446                     if self.interim is True:
    447                         with torch.no_grad():
--> 448                             _ = self.model(*[samples_input[l][k].unsqueeze(0) for l in range(len(X))])
    449                             interim_inputs = self.layer.target_input
    450                             del self.layer.target_input

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/vgg.py in forward(self, x)
     40 
     41     def forward(self, x):
---> 42         x = self.features(x)
     43         x = x.view(x.size(0), -1)
     44         x = self.classifier(x)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py in forward(self, input)
     89     def forward(self, input):
     90         for module in self._modules.values():
---> 91             input = module(input)
     92         return input
     93 

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py in forward(self, input)
    299     def forward(self, input):
    300         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 301                         self.padding, self.dilation, self.groups)
    302 
    303 

RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'
```

**Comment by gabrieltseng** [comment]
Hi Scott,

I added some checks to make sure all tensors are on the right device, so the code you posted should run now.

**Comment by slundberg** [comment]
Thanks! It works for me know. I'll play with it a bit more when I get a chance. The fact that we still pass in the original data even though the model is just from the 7th layer is different than for the TF version. I want to think about that more.

**Comment by slundberg** [comment]
Merging this for now since everything works. We can decide before a release if the API difference between the TF and this version is important.

Thanks again for the great work!

**Comment by gabrieltseng** [comment]
Awesome; thank you!

**Pull request merged**
