### PR TITLE
Custom timeseries xticks in AdditiveForceArrayVisualizer

### PR DESCRIPTION
**Pull request by JasonTam**
Hi,
I love the `AdditiveForceArrayVisualizer`, but sometimes I want to pass in my own xticks instead of the sample index (for the "original sample ordering" option). For example, when doing work with time-series, I'd like to have xticks as dates or whatever.

So I started working on this, and then, as a react/js noob, I ran into a million problems with building using webpack / babel etc. But I still want to surface this PR for discussion.

Thanks

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks! I can see how that would be helpful. Did you manage to get things working?

**Comment by JasonTam** [comment]
Nope =/
Can't seem to build the js portion to debug / test
I'm running `webpack -p` in `javascript/` but running into this error:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
```
Update:
So I had to change `loaders` to `rules` in `webpack.config.js` and a bunch of babel versions -- and it seems I can finally build now (I think).

**Comment by JasonTam** [comment]
So... I was struggling really hard to get arbitrary xticks to work -- so I changed the PR to focus on allowing timeseries xticks. Using `xticks` and `ts_fmt` parameters will change the xticks for the "original sample ordering" option as shown below.
screenshot from 2018-10-28 23-34-26

Aside: I had to modify:
```
	modified:   javascript/package.json
	modified:   javascript/webpack.config.js
```
in order to build `bundle.js` . I can include those changes in another PR ( or this one ).

**Comment by slundberg** [comment]
Could you share what you changed to get it to compile? If I clone a clean version of the repo, cd into the javascript directory, and then run `npm install` followed by `webpack -p` everything builds for me.

The interface seems like a good direction. It seems though that you are not giving xticks so much as keys to sort by (many fewer actual tick marks will be drawn than tick marks that you pass). We could change the name from `xticks` to `ordering_keys` to reflect this. Also, what if instead of encoding then decoding the time string twice we just treat isoformat xtick values as dates (check if parse date with the ISO format (`%Y-%m-%dT%H:%M:%S.%f%z`) works on xticks[0])? Then `ts_fmt` can just become `ordering_keys_format` and get used to format any kind of numbers, not just dates.

**Comment by JasonTam** [comment]
These are the changes I had to make: https://github.com/slundberg/shap/compare/master...JasonTam:babel-ver

I totally see how this is just a `ordering_keys` now. 
But just to test this out, I took a linear ramp of `shap_values`, changed the order and got strange results.
Vanilla ramp:
```
n = 20
start = pd.datetime(2018, 1, 1)
delta = pd.Timedelta(f'{n-1}d')
ts_fmt = '%b %d, %Y'
date_ticks = pd.date_range(start, start + delta).strftime(ts_fmt)
shap_values = np.tile(np.arange(n)[:, None]/n, (1, 2))

shap.initjs()
shap.force_plot(0, 
                shap_values,
                xticks=date_ticks,
                ts_fmt=ts_fmt,)
```
screenshot from 2018-10-30 00-29-48

Swap order of 1st and 2nd half:
```
shap.force_plot(0, 
                shap_values,
                xticks=date_ticks[int(n/2):] + date_ticks[:int(n/2)],
                ts_fmt=ts_fmt,)
```
screenshot from 2018-10-30 00-30-03

I'll try and figure out what's going on here.

UPDATE:
oh duh, we still have this sort:
` explanations = sortBy(this.props.explanations, x => x.origInd);`

**Comment by JasonTam** [comment]
Implemented `ordering_keys`.
screenshot from 2018-11-02 15-27-28

But idk how I feel about the auto timestamp detection / parse. It could mistakenly convert integers into timestamps unless we consider formats _exactly_ matching `%Y-%m-%dT%H:%M:%S.%f%z`. In which case, it's just front-loading effort to convert to that format before touching the shap api.

**Comment by slundberg** [comment]
So as it stand right now we can pass anything as a key right? Then if ts_fmt is not None it will treat them as dates that should be in the ts_fmt? That's fine by me. Could we change ts_fmt though to ordering_keys_time_format? It is a long longer but much clearer I think.

Thanks for sharing all the great work!

**Comment by JasonTam** [comment]
Ok, in the 2 commits above, anything numeric can be passed as an ordering key in addition to a time string if `ordering_keys_time_format` is provided. (and renamed)

Here's a gist of the snippets I've been testing with. Too bad the js won't render
https://gist.github.com/JasonTam/a3ac6d9be56dc341392579ebac2b8bb1

**Comment by slundberg** [comment]
Looks great! Thanks again!

**Pull request merged**
