### PR TITLE
use small bart model

### LINKED ISSUE #3045: MAINT: Improve unit test execution speed
Port of https://github.com/dsgibbons/shap/issues/42

Unit tests currently take ~20 mins to complete. If we could reduce that it could help reduce the time it takes to validate PRs, improving our effectiveness as reviewers.

The pytest logs show the names of the lowest 20 tests, which is a good way to prioritise tests to improve. 

## TODO

- [x] Find a suitable smaller translation model for tests. See #3286
- [ ] (Ongoing) refactor the slowest tests to run faster
- [x] Cache the installation of the dependencies, which currently take several minutes from each test job.
- [x] Investigate parallelising the tests to run on multiple CPUs.
  - WIP attempt abandoned as it seems to actually make the tests run even slower!
- [x] Get CodeCov working, to help us evaluate relevant test coverage when reviewing PRs.

### PR DESCRIPTION
**Pull request by CloseChoice**
## Overview

Works towards #3045 

Description of the changes proposed in this pull request:
- use internal huggingface testing model which is [really small (~140kB)](https://huggingface.co/hf-internal-testing/tiny-random-BartModel/tree/main)

One of the transformers maintainers mentions the (internal-hf-testing) models [here](https://github.com/huggingface/transformers/issues/15308#issuecomment-1022641924) so they should be stable. We could also just republish the model in one of our repositories, if one expresses the wish.

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [x] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Comment by connortann** [comment]
Fantastic spot! This model looks like it could be exactly what we need. Assuming the tests pass, this could shave several minutes off our CI time. Last time we used a small model we saved ~5 mins on each job.

**Comment by connortann** [comment]
Suggest as part of this PR try removing `protobuf` from the test dependencies, in `pyproject.toml`. That was required for the previous "nano" translation model, but it might not be needed now.

**Comment by CloseChoice** [comment]
> Suggest as part of this PR try removing `protobuf` from the test dependencies, in `pyproject.toml`. That was required for the previous "nano" translation model, but it might not be needed now.

That is still needed. My local tests are failing if I remove protobuf

**Review by connortann — APPROVED** [review]
LGTM!

**Pull request merged**
