### PR TITLE
 MAINT: address Matplotlib deprecation warnings in test suite 

### PR DESCRIPTION
**Pull request by znacer**
## Overview

Closes corresponding tasks #3066  

Description of the changes proposed in this pull request:
Removed `vmin` and `vmax` statements in `plt.scatter` for NA values, that are grey anyway.
Changed the statement `plt.tight_layout` to `fig.set_layout_engine("tight")`. This statement is not to be deprecated by matplotlib. Updated the baselines images corresponding.

## Checklist

- [X] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [X] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Comment by connortann** [comment]
Thanks for the PR! A few questions just to check my understanding.

> Changed the statement plt.tight_layout to fig.set_layout_engine("tight"). This statement is not to be deprecated by matplotlib. 

This caught my eye. I couldn't find a deprecation notice for the original function - did you find something in the matplotlib docs suggesting `plt.tight_layout` will be deprecated?

I notice the baseline images have changed very slightly. What causes that change: does `fig.set_layout_engine("tight")` have different behaviour to `plt.tight_laytout`?

**Comment by znacer** [comment]
To be more precise, I first used ‘fig.set_tight_layout(True)‘ to get rid of the warning. This gave a me a depecation warning (https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.set_tight_layout). That is where the ‘fig.set_layout_engine‘ comes from.

**Comment by znacer** [comment]
Concerning the change in the images, I am not sure where it comes from. If you prefer to keep the original images, I suggest to add tolerances to the tests.

**Review by connortann — APPROVED** [review]
Thanks again for the PR - collectively we're making great progress fixing all these warnings.

**Pull request merged**
