### PR TITLE
add args to allow customized tree model

### PR DESCRIPTION
**Pull request by xzzxxzzx**
add args to allow customized tree model. The self.trees will be set by logic outside tree.py.

### CODE REVIEW

**Comment by slundberg** [comment]
I can see why you would want to have customized trees. Would it work to just add support for passing an array of Tree objects? That would match the interface of the other model types.

**Comment by xzzxxzzx** [comment]
Yes, that would work too! Do you want to add it, or should I?

**Comment by slundberg** [comment]
Go for it!

**Comment by slundberg** [comment]
Thanks! Why not just pass the array of trees as the `model` parameter? It is the model, so that will keep it consistent with the other model types.

**Comment by xzzxxzzx** [comment]
Hi Scott, sorry for the late reply. I was out on vacation. I understand your concern about the consistency. In many cases, I have no control of/access to the model implementation, so just like what you did with sklearn, I get the array of trees and pass it into TreeExplainer together with the model. Maybe there's a better way to handle this? please feel free to let me know if you have any suggestions :)

**Comment by slundberg** [comment]
Right, it all looks good to me. The one change for the sake of consistency would be to not have a new keyword argument called `trees` but rather just check if the model object that was passed is an array of Tree objects. Then you can just pass that array of tree objects as though it was the the model (which makes sense because it is the model).

**Comment by slundberg** [comment]
I just changed the code to accept the list of trees directly as the model object and will merge once the unit tests pass.

**Pull request merged**
