### PR TITLE
Added Plotly support for several plots

### LINKED ISSUE #2879: [New Features] Output figures as interactive web components with plotly.py
Hi, I am using shap to visualize machine learning models in my project. I would like to show them on a web page, but shap itself only provides HTML components for the force plot.

To solve this problem, I rewrote some plotting functions using plotly.py which were originally written in `matplotlib`. 
You can see my results here [shap-interactive-plots](https://github.com/zhanghx0905/shap-interactive-plots).
With the help of plotly.py, I can embed the images into web pages as interactive components.

Of course, my implementation is not very general. I don't know if you still have plans to refine the drawing functionality of shap. But I think plotly is a very promising option.

### PR DESCRIPTION
**Pull request by chadmh**
## Overview

Partially Resolves #2879 : Output figures as interactive web components with plotly.py

Description of the changes proposed in this pull request:
Adds Plotly support for the following plots:
- bar
- scatter
- decision
- beeswarm
- heatmap

## Checklist

- [Y] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [Y] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Comment by CloseChoice** [comment]
Thanks for the PR and all the effort you put in this, it is highly appreciated. I think it would be great to have plotly support but honestly I am not sure whether we really can support it on the main shap repository as of now. We value any contribution to this repository highly and your effort here especially but currently we are very short on maintainers and the plots cause a couple of problems, so adding more complexity (and a whole new plotting framework) is too ambitious as of now. 

The following is totally up for discussion:
Maybe the way to go here is to create an extra repository that implements the functionality you have and add more shap plotting functions with plotly support in there. If this proves to be stable, well maintained and used by the community I would like to incorporate it into the main repository. 

@connortann what are your thoughts on this?

**Comment by connortann** [comment]
I agree with your comment @CloseChoice . It's really great to see PRs like this that add new proposed features, and we appreciate the time and effort that has gone in to this. However, as you say, support for multiple plotting backends is not currently in-scope for this repository, and I'd be very hesitant to increase the scope of this repo given the rather precarious situation we are in with limited maintainer time and a large legacy issue tracker.

That said, once we have addressed most of the issues with the `visualisation` tag it would be good to revisit this.

**Comment by connortann** [comment]
Closing for now as "not planned". As above, it would be great to revisit features like this once we have stabilised the new API and improved our test coverage.

**Comment by mtfang** [comment]
I would like to revisit Plotly support. My intended use case is to use shap to create a visualization dashboard for our models and show interactive waterfall or swarm plots with sliders. Because Plotly is developed with Dash, Plotly support would be very useful to whip up some nice interactive dashboard quickly.

**Comment by CloseChoice** [comment]
have you looked into shapash? I think that's what they built

**Pull request closed without merging**
